<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" total="6" passed="6">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="263" started-at="2017-01-11T17:49:14Z" finished-at="2017-01-11T17:49:15Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="263" started-at="2017-01-11T17:49:14Z" finished-at="2017-01-11T17:49:15Z">
      <class name="com.websystique.testng.EmployeeServiceImplTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.websystique.testng.EmployeeServiceImplTest@402f32ff]" name="setUp" is-config="true" duration-ms="167" started-at="2017-01-11T18:49:14Z" finished-at="2017-01-11T18:49:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="deleteEmployeeBySsn()[pri:0, instance:com.websystique.testng.EmployeeServiceImplTest@402f32ff]" name="deleteEmployeeBySsn" duration-ms="15" started-at="2017-01-11T18:49:14Z" finished-at="2017-01-11T18:49:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteEmployeeBySsn -->
        <test-method status="PASS" signature="deleteEmployeeBySsnNotExist()[pri:0, instance:com.websystique.testng.EmployeeServiceImplTest@402f32ff]" name="deleteEmployeeBySsnNotExist" duration-ms="31" started-at="2017-01-11T18:49:14Z" finished-at="2017-01-11T18:49:14Z">
          <exception class="java.lang.RuntimeException">
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteEmployeeBySsnNotExist -->
        <test-method status="PASS" signature="deleteEmployeeBySsnNotExistAgain()[pri:0, instance:com.websystique.testng.EmployeeServiceImplTest@402f32ff]" name="deleteEmployeeBySsnNotExistAgain" duration-ms="1" started-at="2017-01-11T18:49:15Z" finished-at="2017-01-11T18:49:15Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[Item not present]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: Item not present
	at com.websystique.testng.EmployeeServiceImplTest$1.answer(EmployeeServiceImplTest.java:143)
	at org.mockito.internal.stubbing.StubbedInvocationMatcher.answer(StubbedInvocationMatcher.java:34)
	at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:91)
	at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
	at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:38)
	at org.mockito.internal.creation.cglib.MethodInterceptorFilter.intercept(MethodInterceptorFilter.java:59)
	at com.websystique.testng.EmployeeDao$$EnhancerByMockitoWithCGLIB$$f499c09.deleteEmployeeBySsn(<generated>)
	at com.websystique.testng.EmployeeServiceImpl.deleteEmployeeBySsn(EmployeeServiceImpl.java:22)
	at com.websystique.testng.EmployeeServiceImplTest.deleteEmployeeBySsnNotExistAgain(EmployeeServiceImplTest.java:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteEmployeeBySsnNotExistAgain -->
        <test-method status="PASS" signature="findAllEmployees()[pri:0, instance:com.websystique.testng.EmployeeServiceImplTest@402f32ff]" name="findAllEmployees" duration-ms="12" started-at="2017-01-11T18:49:15Z" finished-at="2017-01-11T18:49:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- findAllEmployees -->
        <test-method status="PASS" signature="saveEmployee()[pri:0, instance:com.websystique.testng.EmployeeServiceImplTest@402f32ff]" name="saveEmployee" duration-ms="2" started-at="2017-01-11T18:49:15Z" finished-at="2017-01-11T18:49:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- saveEmployee -->
        <test-method status="PASS" signature="saveExistingEmployee()[pri:0, instance:com.websystique.testng.EmployeeServiceImplTest@402f32ff]" name="saveExistingEmployee" duration-ms="3" started-at="2017-01-11T18:49:15Z" finished-at="2017-01-11T18:49:15Z">
          <exception class="org.mockito.exceptions.misusing.UnfinishedStubbingException">
            <message>
              <![CDATA[
Unfinished stubbing detected here:
-> at com.websystique.testng.EmployeeServiceImplTest.saveExistingEmployee(EmployeeServiceImplTest.java:83)

E.g. thenReturn() may be missing.
Examples of correct stubbing:
    when(mock.isOk()).thenReturn(true);
    when(mock.isOk()).thenThrow(exception);
    doThrow(exception).when(mock).someVoidMethod();
Hints:
 1. missing thenReturn()
 2. you are trying to stub a final method, you naughty developer!
 3: you are stubbing the behaviour of another mock inside before 'thenReturn' instruction if completed
]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.mockito.exceptions.misusing.UnfinishedStubbingException: 
Unfinished stubbing detected here:
-> at com.websystique.testng.EmployeeServiceImplTest.saveExistingEmployee(EmployeeServiceImplTest.java:83)

E.g. thenReturn() may be missing.
Examples of correct stubbing:
    when(mock.isOk()).thenReturn(true);
    when(mock.isOk()).thenThrow(exception);
    doThrow(exception).when(mock).someVoidMethod();
Hints:
 1. missing thenReturn()
 2. you are trying to stub a final method, you naughty developer!
 3: you are stubbing the behaviour of another mock inside before 'thenReturn' instruction if completed

	at com.websystique.testng.EmployeeServiceImplTest.saveExistingEmployee(EmployeeServiceImplTest.java:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- org.mockito.exceptions.misusing.UnfinishedStubbingException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- saveExistingEmployee -->
      </class> <!-- com.websystique.testng.EmployeeServiceImplTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
